name: CI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    branches:
      - "**"

  pull_request:
    branches:
      - "**:**"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        crystal: [1.8.2, latest]  # This needs to be kept in sync with /shards.yml
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install Crystal ${{ matrix.crystal }}
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
          shards: true
      - run: shards install
      - run: crystal spec --order=random --error-on-warnings
      - run: crystal spec -Dpreview_mt --order=random --error-on-warnings
